baseURL: https://t-hishinuma.github.io/
languageCode: ja
theme: pure
title: "Super Test page!!"
publishDir: "../"
copyright: "Toshiaki Hishinuma — All rights reserved."

menu:
  main:
    - identifier: home
      name: Home
      title: Home 
      url: /
      weight: 1

    - identifier: about
      name: About
      title: About
      url: /about
      weight: 2

    - identifier: Publifications
      name: Publifications
      title: Publifications
      url: /pub
      weight: 5

    - identifier: categories
      name: Categories
      title: Categories
      url: /categories
      weight: 3

    - identifier: tags
      name: Tags
      title: Tags
      url: /tags
      weight: 4


  # profile
params:
    since: 2019
    #    enablePostCopyright: true
    mainSections: ["posts"]
    enableMathJax: true #Enable mathjax support, to use mathematical notations
    menuIcons:
        enable: true  # 是否启用导航菜单图标
        home: icon-home-fill
        archives: icon-archives-fill
        categories: icon-folder
        tags: icon-tags
        about: icon-cup-fill
        repository: icon-project
        Publifications: icon-book-fill
        links: icon-friendship

    profile:
     enabled: true
     avatar: "img/avatar.jpg"
     gravatar: hishinuma.toshiaki[at]gmail.com
     author: "Toshiaki Hishinuma"
     author_title: "菱沼のページ"
     author_description: "ここはテスト中だ"
     location: "Tokyo, Japan"
     follow: https://github.com/t-hishinuma
     social:
         links:
             github: https://github.com/t-hishinuma
             twitter: https://twitter.com/Hishinuma_t
             link_tooltip: false # enable the social link tooltip, options: true, false

    site:
        logo:
            enabled: true
            width: 40
            height: 40
            url: favicon.ico
        title: Hugo # 页面title
        favicon: goma.ico
        board: <p>enjoy~</p> # 公告牌
